### PR TITLE
Added Editing of Movie Feature

### PR DESCRIPTION
**Pull request by Sanyam-jain30**
#6 Completed the issue

Changes:
Added a new tree command and function to edit movie night.

Working:

https://github.com/nrossetti/movie-time/assets/78720027/08158e27-ca7a-48e1-b6c0-705e149e54f2

### CODE REVIEW

**Review by nrossetti — APPROVED** [review]
Looks good, thanks for the contribution.

**Comment by nrossetti** [comment]
@Sanyam-jain30 i have also added [shal](https://letterboxd.com/film/sholay/) to my watch list :)

**Comment by Sanyam-jain30** [comment]
Yeah, I know some of them.

**Comment by Sanyam-jain30** [comment]
In this list U-turn and Bhoot Part One: The Haunted Ship from my personal point of view, are the most horror movies.

**Pull request merged**
